const GatewayStatus = {
  SUCCEED: 'P0',
  FAILED_UNKNOWN: 'P1',
  ABORTED: 'P2',
  REFUSED_LIMITER: 'P3',
  REFUSED_UNKNOWN: 'P4',
  QUARANTINE: 'P5',
  EXPIRED: 'P6',
  BLACKLIST: 'P7',
  PROCESS_INITIALIZED: 'P9',
  TRANSACTION_ANTIFRAUD_SUCCEED: 'F0',
  TRANSACTION_ANTIFRAUD_REFUSED: 'F1',
  TRANSACTION_ANTIFRAUD_FAILED: 'F2',
};

module.exports = GatewayStatus;
